use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'KLApplicationEntry_Example' do
  pod 'KLApplicationEntry', :path => '../'

  target 'KLApplicationEntry_Tests' do
    inherit! :search_paths

    
  end
end
