use_frameworks!

platform :ios, '8.0'

target 'KLApplicationEntry_Example' do
  pod 'KLApplicationEntry', :path => '../'

  target 'KLApplicationEntry_Tests' do
    inherit! :search_paths

    
  end
end
